language: en
lang_direction: ltr
landing_page:
  welcome_message:
    text: 'Welcome to our office conference!'
  name_form:
    text: 'Please type group name and the password sent in your mail!' 
    name_placeholder_text: Group name here   
    password_placeholder_text: Password here
    submit_button_text: Submit
navbar:
  title:
    text: Web Conference
text_chat:
  submit_button_text: Submit
  placeholder_text: 'Enter text here'